languages_list = [
    "Afrikaans",
    "Amharic",
    "Arabic",
    "Assamese",
    "Azerbaijani",
    "Azerbaijani - Cyrilic",
    "Belarusian",
    "Bengali",
    "Tibetan",
    "Bosnian",
    "Breton",
    "Bulgarian",
    "Catalan",
    "Valencian",
    "Cebuano",
    "Czech",
    "Chinese - Simplified",
    "Chinese - Traditional",
    "Cherokee",
    "Corsican",
    "Welsh",
    "Danish",
    "Danish - Fraktur",
    "German",
    "German - Fraktur",
    "Dzongkha",
    "Greek - Modern",
    "English",
    "English - Middle",
    "Esperanto",
    "Math",
    "Estonian",
    "Basque",
    "Faroese",
    "Persian",
    "Filipino - Tagalog",
    "Finnish",
    "French",
    "French - Middle",
    "Western Frisian",
    "Scottish Gaelic",
    "Irish",
    "Galician",
    "Greek - Ancient",
    "Gujarati",
    "Haitian",
    "Hebrew",
    "Hindi",
    "Croatian",
    "Hungarian",
    "Armenian",
    "Inuktitut",
    "Indonesian",
    "Icelandic",
    "Italian",
    "Italian - Old",
    "Javanese",
    "Japanese",
    "Kannada",
    "Georgian",
    "Georgian - Old",
    "Kazakh",
    "Central Khmer",
    "Kirghiz",
    "Kurmanji",
    "Korean",
    "Korean - vertical",
    "Kurdish",
    "Lao",
    "Latin",
    "Latvian",
    "Lithuanian",
    "Luxembourgish",
    "Malayalam",
    "Marathi",
    "Macedonian",
    "Maltese",
    "Mongolian",
    "Maori",
    "Malay",
    "Burmese",
    "Nepali",
    "Dutch",
    "Norwegian",
    "Occitan",
    "Oriya",
    "Punjabi",
    "Polish",
    "Portuguese",
    "Pushto",
    "Quechua",
    "Romanian",
    "Russian",
    "Sanskrit",
    "Sinhalese",
    "Slovak",
    "Slovak - Fraktur",
    "Slovenian",
    "Sindhi",
    "Spanish",
    "Castilian - Old",
    "Albanian",
    "Serbian",
    "Serbian - Latin",
    "Sundanese",
    "Swahili",
    "Swedish",
    "Syriac",
    "Tamil",
    "Tatar",
    "Telugu",
    "Tajik",
    "Filipino",
    "Thai",
    "Tigrinya",
    "Tonga",
    "Turkish",
    "Uyghur",
    "Ukrainian",
    "Urdu",
    "Uzbek",
    "Uzbek - Cyrilic",
    "Vietnamese",
    "Yiddish",
    "Yoruba",
    "Arabic",
    "Armenian",
    "Bengali",
    "Cherokee",
    "Cyrillic",
    "Devanagari",
    "Ethiopic",
    "Georgian",
    "Greek",
    "Gujarati",
    "Gurmukhi",
    "Han - simplified",
    "Han simplified vertical",
    "Han traditional",
    "Han traditional vertical",
    "Hangul",
    "Hangul vertical",
    "Hebrew",
    "Japanese",
    "Japanese vertical",
    "Khmer",
    "Myanmar",
    "Oriya",
    "Syriac",
    "Tamil",
    "Telugu",
    "Thaana",
    "Thai",
    "Tibetan",
    "Vietnamese"
]
