language_dictionary = {
'Afrikaans': 'afr',
'Amharic': 'amh',
'Arabic': 'ara',
'Assamese': 'asm',
'Azerbaijani': 'aze',
'Azerbaijani - Cyrilic': 'aze_cyrl',
'Belarusian': 'bel',
'Bengali': 'ben',
'Tibetan': 'bod',
'Bosnian': 'bos',
'Breton': 'bre',
'Bulgarian': 'bul',
'Catalan': 'cat',
'Valencian': 'cat',
'Cebuano': 'ceb',
'Czech': 'ces',
'Chinese - Simplified': 'chi_sim',
'Chinese - Traditional': 'chi_tra',
'Cherokee': 'chr',
'Corsican': 'cos',
'Welsh': 'cym',
'Danish': 'dan',
'Danish - Fraktur': 'dan_frak',
'German': 'deu',
'German - Fraktur': 'deu_frak',
'Dzongkha': 'dzo',
'Greek - Modern': 'ell',
'English': 'eng',
'English - Middle': 'enm',
'Esperanto': 'epo',
'Math': 'equ',
'Estonian': 'est',
'Basque': 'eus',
'Faroese': 'fao',
'Persian': 'fas',
'Filipino - Tagalog': 'fil',
'Finnish': 'fin',
'French': 'fra',
'German - Fraktur': 'frk',
'French - Middle': 'frm',
'Western Frisian': 'fry',
'Scottish Gaelic': 'gla',
'Irish': 'gle',
'Galician': 'glg',
'Greek - Ancient': 'grc',
'Gujarati': 'guj',
'Haitian': 'hat',
'Hebrew': 'heb',
'Hindi': 'hin',
'Croatian': 'hrv',
'Hungarian': 'hun',
'Armenian': 'hye',
'Inuktitut': 'iku',
'Indonesian': 'ind',
'Icelandic': 'isl',
'Italian': 'ita',
'Italian - Old': 'ita_old',
'Javanese': 'jav',
'Japanese': 'jpn',
'Kannada': 'kan',
'Georgian': 'kat',
'Georgian - Old': 'kat_old',
'Kazakh': 'kaz',
'Central Khmer': 'khm',
'Kirghiz; Kyrgyz': 'kir',
'Kurmanji (Kurdish - Latin Script)': 'kmr',
'Korean': 'kor',
'Korean - vertical': 'kor_vert',
'Kurdish': 'kur',
'Lao': 'lao',
'Latin': 'lat',
'Latvian': 'lav',
'Lithuanian': 'lit',
'Luxembourgish': 'ltz',
'Malayalam': 'mal',
'Marathi': 'mar',
'Macedonian': 'mkd',
'Maltese': 'mlt',
'Mongolian': 'mon',
'Maori': 'mri',
'Malay': 'msa',
'Burmese': 'mya',
'Nepali': 'nep',
'Dutch; Flemish': 'nld',
'Norwegian': 'nor',
'Occitan': 'oci',
'Oriya': 'ori',
'Orientation and script detection module': 'osd',
'Punjabi': 'pan',
'Polish': 'pol',
'Portuguese': 'por',
'Pushto': 'pus',
'Quechua': 'que',
'Romanian': 'ron',
'Moldavian': 'ron',
'Russian': 'rus',
'Sanskrit': 'san',
'Sinhala; Sinhalese': 'sin',
'Slovak': 'slk',
'Slovak - Fraktur': 'slk_frak',
'Slovenian': 'slv',
'Sindhi': 'snd',
'Spanish': 'spa',
'Castilian': 'spa',
'Castilian - Old': 'spa_old',
'Albanian': 'sqi',
'Serbian': 'srp',
'Serbian - Latin': 'srp_latn',
'Sundanese': 'sun',
'Swahili': 'swa',
'Swedish': 'swe',
'Syriac': 'syr',
'Tamil': 'tam',
'Tatar': 'tat',
'Telugu': 'tel',
'Tajik': 'tgk',
'Filipino': 'tgl',
'Thai': 'tha',
'Tigrinya': 'tir',
'Tonga': 'ton',
'Turkish': 'tur',
'Uyghur': 'uig',
'Ukrainian': 'ukr',
'Urdu': 'urd',
'Uzbek': 'uzb',
'Uzbek - Cyrilic': 'uzb_cyrl',
'Vietnamese': 'vie',
'Yiddish': 'yid',
'Yoruba': 'yor'}